import http from "k6/http";
import { check, sleep } from "k6";

export const options = {
  stages: [
    { duration: "60s", target: 20 }, // разогрев до 20VUs
    { duration: "2m", target: 20 }, // держим 20 VUs ~20 RPS
    { duration: "60s", target: 0 }, // «остывание»
  ],
  // thresholds: {
  //   http_req_duration: ["p(95)<500"], // 95% < 500 ms
  //   http_req_failed: ["rate<0.01"], // ошибок <1%
  // },
};

// тестируем GET /api/products
function testGetProducts() {
  const res = http.get("http://localhost:5000/api/products");
  check(res, { "GET /api/products 200": (r) => r.status === 200 });
}

// тестируем POST /api/products
function testPostProduct() {
  const payload = JSON.stringify({
    title: "LoadTest",
    category: "OTHER",
    imageUrls: ["https://example.com/img.png"],
    price: 123.45,
    description: "Generated by k6",
  });
  const params = { headers: { "Content-Type": "application/json" } };
  const res = http.post("http://localhost:5000/api/products", payload, params);
  check(res, { "POST /api/products 201": (r) => r.status === 201 });
  return res.json().id;
}

export default function () {
  // 50% GET, 30% POST, 20% GET by ID
  const rnd = Math.random();
  if (rnd < 0.5) {
    testGetProducts();
  } else if (rnd < 0.8) {
    const id = testPostProduct();
    // сразу проверим по ID
    const res = http.get(`http://localhost:5000/api/products/${id}`);
    check(res, { "GET by id 200": (r) => r.status === 200 });
  } else {
    // случайный ID — здесь можно взять заранее созданный
    http.get("http://localhost:5000/api/products/9e4b6615-d6c4-4084-bdfc-3e3be4cb1360");
  }
  sleep(1); // пауза (эмулируем ~1 RPS на VU)
}
