server:
  http_listen_port: 9080 # на каком порту работает?
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # адрес ручки (эндпоинт) для пост запроса

scrape_configs:
  - job_name: docker-logs # название джобы, будет потом фигурировать в графане
    static_configs:
      - targets:
          - localhost # пока что работаем локально
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*log # забираем логи из докер-контейнера. Контейнер работает, логи улетают в stdout и оттуда всех их забираем

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"

      - labels:
          tag:
          image_name:
          container_name:
