global:
  scrape_interval: 3s # интервал скрепинга, как часто прометей будет ходить и собирать метрики

# какие приложение трекаем
scrape_configs:
  - job_name: "monitoring nestjs" # имя джобы
    metrics_path: /metrics # по этому эндпоинту прометей будет запрашивать данные
    static_configs:
      # - targets: ["backend:5000"] # тут имя контейнера, но если приложение будет жить на другом сервере, то можно просто указать ip типо 42.23.23.23 или локальный ip
      - targets: ["host.docker.internal:5000"] # для удобства
