services:
  proxy:
    container_name: reverse-proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    container_name: backend
    image: geelix6/googs-board-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/goods-db
      PORT: 5000
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    image: geelix6/googs-board-frontend:latest


  # monitoring and logging
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./devops/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./devops/loki-config.yaml:/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./devops/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      # - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana


  
  # сервис для миграций в бд
  migrator:
    image: geelix6/googs-board-backend:latest
    container_name: migrator
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "npx prisma migrate deploy"]
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/goods-db"

  db:
    container_name: postgres-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goods-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
  grafana-data:
  prometheus-data: