services:
  proxy:
    container_name: reverse-proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    container_name: backend
    image: geelix6/googs-board-backend2:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/goods-db
      PORT: 5000

  frontend:
    container_name: frontend
    image: geelix6/googs-board-frontend:latest

  
  # сервис для миграций в бд
  migrate:
    image: geelix6/googs-board-backend2:latest
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "npx prisma migrate deploy"]
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/goods-db"

  db:
    container_name: postgres-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goods-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data: