export function convertCategory(category: string): string {
  const translations: Record<string, string> = {
    ELECTRONICS: 'Электроника',
    COMPUTERS: 'Компьютеры и комплектующие',
    MOBILE_PHONES: 'Смартфоны и мобильные устройства',
    AUDIO_VIDEO: 'Аудио и видео техника',
    HOME_APPLIANCES: 'Бытовая техника',
    FASHION: 'Мода и одежда',
    FOOTWEAR: 'Обувь',
    ACCESSORIES: 'Аксессуары (ремни, кошельки, сумки)',
    JEWELRY: 'Украшения',
    BEAUTY: 'Косметика и парфюмерия',
    HEALTH: 'Товары для здоровья',
    SPORTS_EQUIPMENT: 'Спортивные товары',
    OUTDOOR: 'Товары для активного отдыха и туризма',
    AUTOMOTIVE: 'Автотовары и аксессуары',
    HOME_FURNISHING: 'Мебель и интерьер',
    HOME_DECOR: 'Декор для дома',
    KITCHEN: 'Товары для кухни',
    GARDENING: 'Сад и огород',
    PET_SUPPLIES: 'Товары для животных',
    BABY: 'Товары для детей и младенцев',
    TOYS: 'Игрушки и игры',
    BOOKS: 'Книги и учебная литература',
    OFFICE_SUPPLIES: 'Канцелярия и офисные товары',
    MUSIC_INSTRUMENTS: 'Музыкальные инструменты',
    ART_CRAFT: 'Товары для творчества и искусства',
    COLLECTIBLES: 'Коллекционные товары',
    TOOLS: 'Товары для ремонта и строительства',
    GROCERY: 'Продукты питания',
    BEVERAGES: 'Напитки',
    SOFTWARE: 'Программное обеспечение',
    VIDEO_GAMES: 'Видеоигры и консоли',
    OFFICE_EQUIPMENT: 'Офисная техника',
    OTHER: 'Другое',
  }

  return translations[category] || category
}
