-- CreateEnum
CREATE TYPE "Category" AS ENUM ('ELECTRONICS', 'COMPUTERS', 'MOBILE_PHONES', 'AUDIO_VIDEO', 'HOME_APPLIANCES', 'FASHION', 'FOOTWEAR', 'ACCESSORIES', 'JEWELRY', 'BEAUTY', 'HEALTH', 'SPORTS_EQUIPMENT', 'OUTDOOR', 'AUTOMOTIVE', 'HOME_FURNISHING', 'HOME_DECOR', 'KITCHEN', 'GARDENING', 'PET_SUPPLIES', 'BABY', 'TOYS', 'BOOKS', 'OFFICE_SUPPLIES', 'MUSIC_INSTRUMENTS', 'ART_CRAFT', 'COLLECTIBLES', 'TOOLS', 'GROCERY', 'BEVERAGES', 'SOFTWARE', 'VIDEO_GAMES', 'OFFICE_EQUIPMENT', 'OTHER');

-- CreateTable
CREATE TABLE "products" (
    "id" UUID NOT NULL,
    "title" VARCHAR(127) NOT NULL,
    "category" "Category" NOT NULL,
    "image_urls" VARCHAR(255)[],
    "price" DECIMAL(11,2) NOT NULL,
    "description" VARCHAR(8191) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "product_image_count_max_30" CHECK (array_length(image_urls, 1) <= 30)
);
